/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as FinancialenrichmentIndexImport } from './routes/financial_enrichment/index'
import { Route as ContactIndexImport } from './routes/contact/index'
import { Route as CampaignsIndexImport } from './routes/campaigns/index'
import { Route as CampaignsCreateIndexImport } from './routes/campaigns/create/index'
import { Route as CampaignsCampaignIdIndexImport } from './routes/campaigns/$campaignId/index'
import { Route as CampaignsCampaignIdCampaignleadIndexImport } from './routes/campaigns/$campaignId/$campaign_lead/index'

// Create Virtual Routes

const SegmentsIndexLazyImport = createFileRoute('/segments/')()
const LeadsIndexLazyImport = createFileRoute('/leads/')()
const IntegrationsIndexLazyImport = createFileRoute('/integrations/')()
const EnrichmentIndexLazyImport = createFileRoute('/enrichment/')()
const DiscoverIndexLazyImport = createFileRoute('/discover/')()
const AudiencesIndexLazyImport = createFileRoute('/audiences/')()
const AicallingIndexLazyImport = createFileRoute('/ai_calling/')()
const DashboardIndexLazyImport = createFileRoute('/_dashboard/')()
const SegmentsUpdateLazyImport = createFileRoute('/segments/update')()
const SegmentsSegmentIdIndexLazyImport = createFileRoute(
  '/segments/$segmentId/',
)()
const AudiencesAudienceIdIndexLazyImport = createFileRoute(
  '/audiences/$audienceId/',
)()
const AicallingCampaignIdIndexLazyImport = createFileRoute(
  '/ai_calling/$campaignId/',
)()

// Create/Update Routes

const SegmentsIndexLazyRoute = SegmentsIndexLazyImport.update({
  id: '/segments/',
  path: '/segments/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/segments/index.lazy').then((d) => d.Route),
)

const LeadsIndexLazyRoute = LeadsIndexLazyImport.update({
  id: '/leads/',
  path: '/leads/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/leads/index.lazy').then((d) => d.Route))

const IntegrationsIndexLazyRoute = IntegrationsIndexLazyImport.update({
  id: '/integrations/',
  path: '/integrations/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/integrations/index.lazy').then((d) => d.Route),
)

const EnrichmentIndexLazyRoute = EnrichmentIndexLazyImport.update({
  id: '/enrichment/',
  path: '/enrichment/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/enrichment/index.lazy').then((d) => d.Route),
)

const DiscoverIndexLazyRoute = DiscoverIndexLazyImport.update({
  id: '/discover/',
  path: '/discover/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/discover/index.lazy').then((d) => d.Route),
)

const AudiencesIndexLazyRoute = AudiencesIndexLazyImport.update({
  id: '/audiences/',
  path: '/audiences/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/audiences/index.lazy').then((d) => d.Route),
)

const AicallingIndexLazyRoute = AicallingIndexLazyImport.update({
  id: '/ai_calling/',
  path: '/ai_calling/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/ai_calling/index.lazy').then((d) => d.Route),
)

const DashboardIndexLazyRoute = DashboardIndexLazyImport.update({
  id: '/_dashboard/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/_dashboard/index.lazy').then((d) => d.Route),
)

const FinancialenrichmentIndexRoute = FinancialenrichmentIndexImport.update({
  id: '/financial_enrichment/',
  path: '/financial_enrichment/',
  getParentRoute: () => rootRoute,
} as any)

const ContactIndexRoute = ContactIndexImport.update({
  id: '/contact/',
  path: '/contact/',
  getParentRoute: () => rootRoute,
} as any)

const CampaignsIndexRoute = CampaignsIndexImport.update({
  id: '/campaigns/',
  path: '/campaigns/',
  getParentRoute: () => rootRoute,
} as any)

const SegmentsUpdateLazyRoute = SegmentsUpdateLazyImport.update({
  id: '/segments/update',
  path: '/segments/update',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/segments/update.lazy').then((d) => d.Route),
)

const SegmentsSegmentIdIndexLazyRoute = SegmentsSegmentIdIndexLazyImport.update(
  {
    id: '/segments/$segmentId/',
    path: '/segments/$segmentId/',
    getParentRoute: () => rootRoute,
  } as any,
).lazy(() =>
  import('./routes/segments/$segmentId/index.lazy').then((d) => d.Route),
)

const AudiencesAudienceIdIndexLazyRoute =
  AudiencesAudienceIdIndexLazyImport.update({
    id: '/audiences/$audienceId/',
    path: '/audiences/$audienceId/',
    getParentRoute: () => rootRoute,
  } as any).lazy(() =>
    import('./routes/audiences/$audienceId/index.lazy').then((d) => d.Route),
  )

const AicallingCampaignIdIndexLazyRoute =
  AicallingCampaignIdIndexLazyImport.update({
    id: '/ai_calling/$campaignId/',
    path: '/ai_calling/$campaignId/',
    getParentRoute: () => rootRoute,
  } as any).lazy(() =>
    import('./routes/ai_calling/$campaignId/index.lazy').then((d) => d.Route),
  )

const CampaignsCreateIndexRoute = CampaignsCreateIndexImport.update({
  id: '/campaigns/create/',
  path: '/campaigns/create/',
  getParentRoute: () => rootRoute,
} as any)

const CampaignsCampaignIdIndexRoute = CampaignsCampaignIdIndexImport.update({
  id: '/campaigns/$campaignId/',
  path: '/campaigns/$campaignId/',
  getParentRoute: () => rootRoute,
} as any)

const CampaignsCampaignIdCampaignleadIndexRoute =
  CampaignsCampaignIdCampaignleadIndexImport.update({
    id: '/campaigns/$campaignId/$campaign_lead/',
    path: '/campaigns/$campaignId/$campaign_lead/',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/segments/update': {
      id: '/segments/update'
      path: '/segments/update'
      fullPath: '/segments/update'
      preLoaderRoute: typeof SegmentsUpdateLazyImport
      parentRoute: typeof rootRoute
    }
    '/campaigns/': {
      id: '/campaigns/'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof CampaignsIndexImport
      parentRoute: typeof rootRoute
    }
    '/contact/': {
      id: '/contact/'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactIndexImport
      parentRoute: typeof rootRoute
    }
    '/financial_enrichment/': {
      id: '/financial_enrichment/'
      path: '/financial_enrichment'
      fullPath: '/financial_enrichment'
      preLoaderRoute: typeof FinancialenrichmentIndexImport
      parentRoute: typeof rootRoute
    }
    '/_dashboard/': {
      id: '/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/ai_calling/': {
      id: '/ai_calling/'
      path: '/ai_calling'
      fullPath: '/ai_calling'
      preLoaderRoute: typeof AicallingIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/audiences/': {
      id: '/audiences/'
      path: '/audiences'
      fullPath: '/audiences'
      preLoaderRoute: typeof AudiencesIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/discover/': {
      id: '/discover/'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/enrichment/': {
      id: '/enrichment/'
      path: '/enrichment'
      fullPath: '/enrichment'
      preLoaderRoute: typeof EnrichmentIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/integrations/': {
      id: '/integrations/'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/leads/': {
      id: '/leads/'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/segments/': {
      id: '/segments/'
      path: '/segments'
      fullPath: '/segments'
      preLoaderRoute: typeof SegmentsIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/campaigns/$campaignId/': {
      id: '/campaigns/$campaignId/'
      path: '/campaigns/$campaignId'
      fullPath: '/campaigns/$campaignId'
      preLoaderRoute: typeof CampaignsCampaignIdIndexImport
      parentRoute: typeof rootRoute
    }
    '/campaigns/create/': {
      id: '/campaigns/create/'
      path: '/campaigns/create'
      fullPath: '/campaigns/create'
      preLoaderRoute: typeof CampaignsCreateIndexImport
      parentRoute: typeof rootRoute
    }
    '/ai_calling/$campaignId/': {
      id: '/ai_calling/$campaignId/'
      path: '/ai_calling/$campaignId'
      fullPath: '/ai_calling/$campaignId'
      preLoaderRoute: typeof AicallingCampaignIdIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/audiences/$audienceId/': {
      id: '/audiences/$audienceId/'
      path: '/audiences/$audienceId'
      fullPath: '/audiences/$audienceId'
      preLoaderRoute: typeof AudiencesAudienceIdIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/segments/$segmentId/': {
      id: '/segments/$segmentId/'
      path: '/segments/$segmentId'
      fullPath: '/segments/$segmentId'
      preLoaderRoute: typeof SegmentsSegmentIdIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/campaigns/$campaignId/$campaign_lead/': {
      id: '/campaigns/$campaignId/$campaign_lead/'
      path: '/campaigns/$campaignId/$campaign_lead'
      fullPath: '/campaigns/$campaignId/$campaign_lead'
      preLoaderRoute: typeof CampaignsCampaignIdCampaignleadIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/segments/update': typeof SegmentsUpdateLazyRoute
  '/campaigns': typeof CampaignsIndexRoute
  '/contact': typeof ContactIndexRoute
  '/financial_enrichment': typeof FinancialenrichmentIndexRoute
  '/': typeof DashboardIndexLazyRoute
  '/ai_calling': typeof AicallingIndexLazyRoute
  '/audiences': typeof AudiencesIndexLazyRoute
  '/discover': typeof DiscoverIndexLazyRoute
  '/enrichment': typeof EnrichmentIndexLazyRoute
  '/integrations': typeof IntegrationsIndexLazyRoute
  '/leads': typeof LeadsIndexLazyRoute
  '/segments': typeof SegmentsIndexLazyRoute
  '/campaigns/$campaignId': typeof CampaignsCampaignIdIndexRoute
  '/campaigns/create': typeof CampaignsCreateIndexRoute
  '/ai_calling/$campaignId': typeof AicallingCampaignIdIndexLazyRoute
  '/audiences/$audienceId': typeof AudiencesAudienceIdIndexLazyRoute
  '/segments/$segmentId': typeof SegmentsSegmentIdIndexLazyRoute
  '/campaigns/$campaignId/$campaign_lead': typeof CampaignsCampaignIdCampaignleadIndexRoute
}

export interface FileRoutesByTo {
  '/segments/update': typeof SegmentsUpdateLazyRoute
  '/campaigns': typeof CampaignsIndexRoute
  '/contact': typeof ContactIndexRoute
  '/financial_enrichment': typeof FinancialenrichmentIndexRoute
  '/': typeof DashboardIndexLazyRoute
  '/ai_calling': typeof AicallingIndexLazyRoute
  '/audiences': typeof AudiencesIndexLazyRoute
  '/discover': typeof DiscoverIndexLazyRoute
  '/enrichment': typeof EnrichmentIndexLazyRoute
  '/integrations': typeof IntegrationsIndexLazyRoute
  '/leads': typeof LeadsIndexLazyRoute
  '/segments': typeof SegmentsIndexLazyRoute
  '/campaigns/$campaignId': typeof CampaignsCampaignIdIndexRoute
  '/campaigns/create': typeof CampaignsCreateIndexRoute
  '/ai_calling/$campaignId': typeof AicallingCampaignIdIndexLazyRoute
  '/audiences/$audienceId': typeof AudiencesAudienceIdIndexLazyRoute
  '/segments/$segmentId': typeof SegmentsSegmentIdIndexLazyRoute
  '/campaigns/$campaignId/$campaign_lead': typeof CampaignsCampaignIdCampaignleadIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/segments/update': typeof SegmentsUpdateLazyRoute
  '/campaigns/': typeof CampaignsIndexRoute
  '/contact/': typeof ContactIndexRoute
  '/financial_enrichment/': typeof FinancialenrichmentIndexRoute
  '/_dashboard/': typeof DashboardIndexLazyRoute
  '/ai_calling/': typeof AicallingIndexLazyRoute
  '/audiences/': typeof AudiencesIndexLazyRoute
  '/discover/': typeof DiscoverIndexLazyRoute
  '/enrichment/': typeof EnrichmentIndexLazyRoute
  '/integrations/': typeof IntegrationsIndexLazyRoute
  '/leads/': typeof LeadsIndexLazyRoute
  '/segments/': typeof SegmentsIndexLazyRoute
  '/campaigns/$campaignId/': typeof CampaignsCampaignIdIndexRoute
  '/campaigns/create/': typeof CampaignsCreateIndexRoute
  '/ai_calling/$campaignId/': typeof AicallingCampaignIdIndexLazyRoute
  '/audiences/$audienceId/': typeof AudiencesAudienceIdIndexLazyRoute
  '/segments/$segmentId/': typeof SegmentsSegmentIdIndexLazyRoute
  '/campaigns/$campaignId/$campaign_lead/': typeof CampaignsCampaignIdCampaignleadIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/segments/update'
    | '/campaigns'
    | '/contact'
    | '/financial_enrichment'
    | '/'
    | '/ai_calling'
    | '/audiences'
    | '/discover'
    | '/enrichment'
    | '/integrations'
    | '/leads'
    | '/segments'
    | '/campaigns/$campaignId'
    | '/campaigns/create'
    | '/ai_calling/$campaignId'
    | '/audiences/$audienceId'
    | '/segments/$segmentId'
    | '/campaigns/$campaignId/$campaign_lead'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/segments/update'
    | '/campaigns'
    | '/contact'
    | '/financial_enrichment'
    | '/'
    | '/ai_calling'
    | '/audiences'
    | '/discover'
    | '/enrichment'
    | '/integrations'
    | '/leads'
    | '/segments'
    | '/campaigns/$campaignId'
    | '/campaigns/create'
    | '/ai_calling/$campaignId'
    | '/audiences/$audienceId'
    | '/segments/$segmentId'
    | '/campaigns/$campaignId/$campaign_lead'
  id:
    | '__root__'
    | '/segments/update'
    | '/campaigns/'
    | '/contact/'
    | '/financial_enrichment/'
    | '/_dashboard/'
    | '/ai_calling/'
    | '/audiences/'
    | '/discover/'
    | '/enrichment/'
    | '/integrations/'
    | '/leads/'
    | '/segments/'
    | '/campaigns/$campaignId/'
    | '/campaigns/create/'
    | '/ai_calling/$campaignId/'
    | '/audiences/$audienceId/'
    | '/segments/$segmentId/'
    | '/campaigns/$campaignId/$campaign_lead/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  SegmentsUpdateLazyRoute: typeof SegmentsUpdateLazyRoute
  CampaignsIndexRoute: typeof CampaignsIndexRoute
  ContactIndexRoute: typeof ContactIndexRoute
  FinancialenrichmentIndexRoute: typeof FinancialenrichmentIndexRoute
  DashboardIndexLazyRoute: typeof DashboardIndexLazyRoute
  AicallingIndexLazyRoute: typeof AicallingIndexLazyRoute
  AudiencesIndexLazyRoute: typeof AudiencesIndexLazyRoute
  DiscoverIndexLazyRoute: typeof DiscoverIndexLazyRoute
  EnrichmentIndexLazyRoute: typeof EnrichmentIndexLazyRoute
  IntegrationsIndexLazyRoute: typeof IntegrationsIndexLazyRoute
  LeadsIndexLazyRoute: typeof LeadsIndexLazyRoute
  SegmentsIndexLazyRoute: typeof SegmentsIndexLazyRoute
  CampaignsCampaignIdIndexRoute: typeof CampaignsCampaignIdIndexRoute
  CampaignsCreateIndexRoute: typeof CampaignsCreateIndexRoute
  AicallingCampaignIdIndexLazyRoute: typeof AicallingCampaignIdIndexLazyRoute
  AudiencesAudienceIdIndexLazyRoute: typeof AudiencesAudienceIdIndexLazyRoute
  SegmentsSegmentIdIndexLazyRoute: typeof SegmentsSegmentIdIndexLazyRoute
  CampaignsCampaignIdCampaignleadIndexRoute: typeof CampaignsCampaignIdCampaignleadIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  SegmentsUpdateLazyRoute: SegmentsUpdateLazyRoute,
  CampaignsIndexRoute: CampaignsIndexRoute,
  ContactIndexRoute: ContactIndexRoute,
  FinancialenrichmentIndexRoute: FinancialenrichmentIndexRoute,
  DashboardIndexLazyRoute: DashboardIndexLazyRoute,
  AicallingIndexLazyRoute: AicallingIndexLazyRoute,
  AudiencesIndexLazyRoute: AudiencesIndexLazyRoute,
  DiscoverIndexLazyRoute: DiscoverIndexLazyRoute,
  EnrichmentIndexLazyRoute: EnrichmentIndexLazyRoute,
  IntegrationsIndexLazyRoute: IntegrationsIndexLazyRoute,
  LeadsIndexLazyRoute: LeadsIndexLazyRoute,
  SegmentsIndexLazyRoute: SegmentsIndexLazyRoute,
  CampaignsCampaignIdIndexRoute: CampaignsCampaignIdIndexRoute,
  CampaignsCreateIndexRoute: CampaignsCreateIndexRoute,
  AicallingCampaignIdIndexLazyRoute: AicallingCampaignIdIndexLazyRoute,
  AudiencesAudienceIdIndexLazyRoute: AudiencesAudienceIdIndexLazyRoute,
  SegmentsSegmentIdIndexLazyRoute: SegmentsSegmentIdIndexLazyRoute,
  CampaignsCampaignIdCampaignleadIndexRoute:
    CampaignsCampaignIdCampaignleadIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/segments/update",
        "/campaigns/",
        "/contact/",
        "/financial_enrichment/",
        "/_dashboard/",
        "/ai_calling/",
        "/audiences/",
        "/discover/",
        "/enrichment/",
        "/integrations/",
        "/leads/",
        "/segments/",
        "/campaigns/$campaignId/",
        "/campaigns/create/",
        "/ai_calling/$campaignId/",
        "/audiences/$audienceId/",
        "/segments/$segmentId/",
        "/campaigns/$campaignId/$campaign_lead/"
      ]
    },
    "/segments/update": {
      "filePath": "segments/update.lazy.tsx"
    },
    "/campaigns/": {
      "filePath": "campaigns/index.tsx"
    },
    "/contact/": {
      "filePath": "contact/index.tsx"
    },
    "/financial_enrichment/": {
      "filePath": "financial_enrichment/index.tsx"
    },
    "/_dashboard/": {
      "filePath": "_dashboard/index.lazy.tsx"
    },
    "/ai_calling/": {
      "filePath": "ai_calling/index.lazy.tsx"
    },
    "/audiences/": {
      "filePath": "audiences/index.lazy.tsx"
    },
    "/discover/": {
      "filePath": "discover/index.lazy.tsx"
    },
    "/enrichment/": {
      "filePath": "enrichment/index.lazy.tsx"
    },
    "/integrations/": {
      "filePath": "integrations/index.lazy.tsx"
    },
    "/leads/": {
      "filePath": "leads/index.lazy.tsx"
    },
    "/segments/": {
      "filePath": "segments/index.lazy.tsx"
    },
    "/campaigns/$campaignId/": {
      "filePath": "campaigns/$campaignId/index.tsx"
    },
    "/campaigns/create/": {
      "filePath": "campaigns/create/index.tsx"
    },
    "/ai_calling/$campaignId/": {
      "filePath": "ai_calling/$campaignId/index.lazy.tsx"
    },
    "/audiences/$audienceId/": {
      "filePath": "audiences/$audienceId/index.lazy.tsx"
    },
    "/segments/$segmentId/": {
      "filePath": "segments/$segmentId/index.lazy.tsx"
    },
    "/campaigns/$campaignId/$campaign_lead/": {
      "filePath": "campaigns/$campaignId/$campaign_lead/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
